#!/usr/bin/env bash
#
#  Copyright 2021 Jerome DE LUCCHI
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

ELASTICSEARCH_PROTO="http"
ELASTICSEARCH_HOSTNAME="192.168.168.17"
ELASTICSEARCH_PORT="9200"

# DELETE SCHEDULER
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/blast_obj_scheduler
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/blast_obj_scheduler

# DELETE STATISTIC
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/blast_statistic
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/blast_statistic

# DELETE ACCOUNT
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/blast_account
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/blast_account

# DELETE CLUSTER
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/blast_obj_cluster
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/blast_obj_cluster

# DELETE INFRASTRUCTURE
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/blast_obj_infrastructure
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/blast_obj_infrastructure

# DELETE SCRIPT
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/blast_obj_script
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/blast_obj_script

# DELETE SCRIPTLANG
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/script_lang
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/script_lang

# DELETE SETTING
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/blast_setting
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/blast_setting

# DELETE MAPPING
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/port_map
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/port_map

# DELETE REALM
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/blast_realm
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/blast_realm

# DELETE NODE
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/blast_obj_node
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/blast_obj_node

# DELETE NODE
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/blast_obj_node_type
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/blast_obj_node_type

# DELETE NODE
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/blast_obj_node_mode
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/blast_obj_node_mode

# DELETE SCENARIO
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/blast_obj_scenario
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/blast_obj_scenario

# DELETE REPORT
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/blast_obj_report
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/blast_obj_report

# DELETE REQUEST
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/blast_request
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/blast_request