#!/usr/bin/env bash
#
#  Copyright 2020 Jerome DE LUCCHI
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

ELASTICSEARCH_PROTO="http"
ELASTICSEARCH_HOSTNAME="192.168.168.17"
ELASTICSEARCH_PORT="9200"

# DELETE SCHEDULER
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/scheduler
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/scheduler

# DELETE STATISTIC
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/statistic
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/statistic

# DELETE ACCOUNT
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/account
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/account

# DELETE CLUSTER
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/cluster
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/cluster

# DELETE INFRASTRUCTURE
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/infrastructure
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/infrastructure

# DELETE SCRIPT
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/script
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/script

# DELETE SCRIPTLANG
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/scriptlang
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/scriptlang

# DELETE SETTING
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/setting
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/setting

# DELETE MAPPING
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/portmap
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/portmap

# DELETE REALM
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/realm
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/realm

# DELETE NODE
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/node
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/node

# DELETE SCENARIO
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/scenario
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/scenario

# DELETE REPORT
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/report
curl -s -XDELETE ${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}/_template/report